### ISSUE TITLE
Trying to run locally

### ISSUE THREAD

**Issue by arturitu** [borismus/copresence-vr#1]
- First, I downloaded the gh-pages branch & I needed to install 'derequire' & 'watchify' manually, it was good to be added to package.json? or it is understood that must be installed globally?
- To prevent a warn, I added this to package.json:
  `"repository" : {
  "type" : "git",
  "url" : "https://github.com/borismus/copresence-vr.git"
  }`
- After this, I executed 'npm run watch' & 'npm run build' correctly.
- I launched via a local server environment (I use MAMP) and seems to work well on desktop, but when I connected via wifi with an Android device but redirect to a secure layer: https://myip/copresence-vr/ and doesn't work. Is is possible to test locally, or is necessary to be tested under ssl could you recommend me some workflow to dev/test things?

Thanks,

**Comment by borismus** [comment]
I have derequire and watchify installed globally. I guess they could also go into devDependencies, not sure about best practice there.

Thanks for that fix, PR would be great.

What's the error you're seeing? I usually develop over USB debugging via chrome:inspect.

**Comment by arturitu** [comment]
Ok, I installed globally too then.

I'll make a PR in a moment.

I use USB debugging & inspect via chrome too but my problem was with Apache's MAMP configuration, now I have installed [https://www.npmjs.com/package/http-server](url) and works without errors with https.
